"""Compose synthetic probe conversations from data/scenarios.json.

Structure per conversation:
  system | early (filler) | MIDDLE (plants + filler, later evicted) | tail
  (referent/sense tail-use fragments + filler) | final assistant message
  (doubles as a held-out continuation for teacher-forced scoring).

Assistant replies are generated by the dev model in-context (sampled,
seeded), so tail replies are computed with full history — their meaning
as-written is exactly what the experiment tries to preserve.

Incremental generation with one growing cache. The Qwen3-2507 template adds
an empty <think> block to the generation prompt that is absent from the
canonical (non-final) rendering of the same assistant message, so after each
reply we truncate the cache back to the canonical prefix and re-prefill the
reply in canonical form. Canonical-prefix identity is asserted every turn.

Output per scenario: data/synthetic/<id>.json with messages, section
boundaries (message indices), token counts, plants (verbatim from the
scenario), and generation metadata.
"""

import json
import random
import sys
from pathlib import Path

import mlx.core as mx
from mlx_lm import load

sys.path.insert(0, "src")
from kvlib import extend_cache, sampled_generate, truncate_cache
from mlx_lm.models.cache import KVCache

MODEL = "mlx-community/Qwen3-4B-Instruct-2507-4bit"
MAX_REPLY_TOKENS = 420
TEMP = 0.7


def render(tokenizer, msgs, gen_prompt):
    return tokenizer.apply_chat_template(
        msgs, add_generation_prompt=gen_prompt, tokenize=True
    )


class ConversationBuilder:
    def __init__(self, model, tokenizer, system_text):
        self.model = model
        self.tokenizer = tokenizer
        self.msgs = [{"role": "system", "content": system_text}]
        self.cache = [KVCache() for _ in range(len(model.layers))]
        self.stream = []  # canonical token ids prefilled so far
        self.eos_ids = set(tokenizer.eos_token_ids or [tokenizer.eos_token_id])
        self.truncated_replies = 0

    def user_turn_and_reply(self, user_text):
        self.msgs.append({"role": "user", "content": user_text})
        r_gen = render(self.tokenizer, self.msgs, gen_prompt=True)
        r_canon = render(self.tokenizer, self.msgs, gen_prompt=False)
        assert r_gen[: len(self.stream)] == self.stream, "canonical prefix broke (gen)"
        assert r_canon == r_gen[: len(r_canon)], "gen render doesn't extend canonical"

        # prefill user block + generation prompt, sample a reply
        logits = extend_cache(self.model, self.cache, r_gen[len(self.stream):])
        reply_ids = sampled_generate(
            self.model, self.cache, logits, MAX_REPLY_TOKENS, self.eos_ids, TEMP
        )
        if len(reply_ids) == MAX_REPLY_TOKENS:
            self.truncated_replies += 1
        reply_text = self.tokenizer.decode(reply_ids).strip()
        self.msgs.append({"role": "assistant", "content": reply_text})

        # rebuild cache in canonical form: canonical rendering of the now
        # non-final assistant message (no <think> block)
        r_new = render(self.tokenizer, self.msgs, gen_prompt=False)
        # everything after the shared canonical prefix gets re-prefilled;
        # shared prefix = r_canon (user-final canonical render) extended by
        # whatever of the assistant header both renderings share. Simplest
        # robust choice: truncate to r_canon and re-prefill the assistant block.
        assert r_new[: len(r_canon)] == r_canon, "assistant block changed the prefix"
        truncate_cache(self.cache, len(r_canon))
        extend_cache(self.model, self.cache, r_new[len(r_canon):])
        self.stream = r_new
        return reply_text

    def n_tokens(self):
        return len(self.stream)


def compose(scenario, model, tokenizer, seed):
    mx.random.seed(seed)
    rng = random.Random(seed)
    b = ConversationBuilder(model, tokenizer, scenario["system"])

    for t in scenario["early_user_turns"]:
        b.user_turn_and_reply(t)
    early_end = len(b.msgs)
    early_tokens = b.n_tokens()

    # middle: interleave plant turns with filler, deterministic shuffle of
    # plant order; filler turns anchor the subtopic flow in order.
    plants = list(scenario["plants"])
    rng.shuffle(plants)
    fillers = list(scenario["middle_filler_user_turns"])
    seq = []
    pi, fi = 0, 0
    while pi < len(plants) or fi < len(fillers):
        if fi < len(fillers):
            seq.append(("filler", fillers[fi])); fi += 1
        for _ in range(3):  # ~3 plants between fillers → 10 plants / 4 fillers
            if pi < len(plants):
                seq.append(("plant", plants[pi])); pi += 1
    for kind, item in seq:
        b.user_turn_and_reply(item["middle_user"] if kind == "plant" else item)
    middle_end = len(b.msgs)
    middle_tokens = b.n_tokens()

    # tail: filler[0], tail-use fragments (referent + sense), filler[1]
    tail_frags = [p["tail_user_fragment"] for p in scenario["plants"]
                  if p.get("tail_user_fragment")]
    rng.shuffle(tail_frags)
    tail_seq = [scenario["tail_filler_user_turns"][0], *tail_frags,
                scenario["tail_filler_user_turns"][1]]
    for t in tail_seq:
        b.user_turn_and_reply(t)

    return {
        "id": scenario["id"],
        "title": scenario["title"],
        "messages": b.msgs,
        "sections": {
            "early_end_msg": early_end,
            "middle_end_msg": middle_end,
            "early_end_tokens": early_tokens,
            "middle_end_tokens": middle_tokens,
            "total_tokens": b.n_tokens(),
        },
        "plants": scenario["plants"],
        "meta": {
            "model": MODEL, "seed": seed, "temp": TEMP,
            "truncated_replies": b.truncated_replies,
        },
    }


def main(only_ids=None):
    scenarios = json.load(open("data/scenarios.json"))
    model, tokenizer = load(MODEL)
    outdir = Path("data/synthetic")
    outdir.mkdir(parents=True, exist_ok=True)
    for i, sc in enumerate(scenarios):
        if only_ids and sc["id"] not in only_ids:
            continue
        out = outdir / f"{sc['id']}.json"
        if out.exists():
            print(f"{sc['id']}: exists, skipping")
            continue
        conv = compose(sc, model, tokenizer, seed=1000 + i)
        json.dump(conv, open(out, "w"), indent=1, ensure_ascii=False)
        s = conv["sections"]
        print(f"{sc['id']}: {len(conv['messages'])} msgs, {s['total_tokens']} tokens "
              f"(early {s['early_end_tokens']}, middle {s['middle_end_tokens']}), "
              f"truncated={conv['meta']['truncated_replies']}")


if __name__ == "__main__":
    main(set(sys.argv[1:]) or None)
