"""Tokenizer-only mechanical validation for powered successor v13.

This layer is deliberately unpaid and treatment blind.  Its aggregate helper
materializes only the recipe's exact out-of-pool development sentinels; it does
not enumerate, rank, permute, or expand a production-pool candidate.  A pass is
mechanical evidence for the template/tokenizer apparatus, never execution
authorization.

The carrier gate is pure with respect to the subject model: callers supply the
already-produced text, content token IDs, termination token, and cap flag.  The
gate only validates those inputs with the pinned production tokenizer.
"""

from __future__ import annotations

from dataclasses import asdict
import hashlib
from importlib.metadata import PackageNotFoundError, version as package_version
import math
from pathlib import Path
import re
from types import MappingProxyType
from typing import Any, Mapping, Sequence
import unicodedata

from arms_common import canonical_ids_any, render_hf
from powered_v13_recipe import (
    STRATA,
    canonical_json_bytes,
    materialize_development_sentinel,
    recipe_definition,
    validate_fixture_schema,
)
from powered_v13_schema import (
    CARRIER_REQUEST,
    DESIGN_ID,
    MODEL_ID,
    MODEL_REVISION,
    CarrierRegions,
    FreshDestinationPlan,
    ReplayPlan,
    V13SchemaError,
    require_matching_geometry,
)
from powered_v13_tokens import (
    build_fresh_destination_plan,
    build_probe_generation_prefix,
    build_role_native_plan,
    build_turn_aligned_plan,
    complete_source_messages,
    message_starts,
    probe_target_ids,
    source_noncarrier_token_count,
)


STIMULI_SCHEMA = "coherent-state-powered-successor-v13-tokenizer-mechanical-v1"
FORBIDDEN_SURFACE_SCHEMA = "powered-v13-carrier-forbidden-surface-expansion-v2"
CARRIER_ATTEMPT_SCHEMA = "powered-v13-carrier-attempt-spec-v1"
TARGET_BANK_SCHEMA = "powered-v13-production-target-bank-qualification-v1"

# This is a completed, deterministic development-only carrier.  It satisfies
# the production word/token bounds but was not generated by the subject and is
# never a scientific render.
FROZEN_TEST_CARRIER_CONTENT = (
    "The earlier exchange established shared operating context and confirmed "
    "that decision criteria were recorded. This handoff preserves continuity "
    "for the next assistant while withholding the criteria themselves and "
    "every settled detail. Continue from the visible conversation, using the "
    "available context for any later request."
)

NONCARRIER_TOKEN_BOUNDS = (940, 1180)
COMPLETED_SOURCE_TOKEN_BOUNDS = (900, 1400)
CARRIER_WORD_BOUNDS = (40, 60)
CARRIER_TOKEN_BOUNDS = (40, 80)
CARRIER_RENDER_INDICES = (1, 2)
CARRIER_ATTEMPT_INDICES = (1, 2, 3)
CARRIER_MAX_ATTEMPTS_PER_RENDER = 3
CARRIER_Q_CALL_WIDTH = 1
CARRIER_TEMPERATURE = 0.7
CARRIER_TOP_P = 0.95
CARRIER_TOP_K = None
CARRIER_CONTENT_TOKEN_CAP = 80
# ``generated_content_ids`` excludes the terminal EOS.  A carrier may contain
# all 80 allowed content tokens and then emit EOS on one final q=1 witness
# call, so the frozen execution loop has at most 81 sampling calls.  The
# historical public name is retained as an exact content-cap alias; it must
# never be interpreted as a Transformers cap that includes EOS.
CARRIER_MAX_NEW_TOKENS = CARRIER_CONTENT_TOKEN_CAP
CARRIER_MAX_SAMPLING_CALLS = CARRIER_CONTENT_TOKEN_CAP + 1
MAX_PREFILL_CALL_TOKENS = 4096

# Hashes observed from the exact tokenizer files at MODEL_REVISION.  Name alone
# is not a sufficient binding because a mutable local cache can retain it while
# changing vocabulary or chat-template behavior.
PINNED_TOKENIZER_VOCAB_SHA256 = (
    "f488fa45d324a8bc64c84f0e27b47223872d550f2a6900564f77dfa67ca5ff4d"
)
PINNED_CHAT_TEMPLATE_SHA256 = (
    "64f85b198065d0fba2a81f37e10ed68161ce2c19a754c7100e67e0ca2ee9c326"
)
PINNED_TOKENIZER_BACKEND_SHA256 = (
    "41e00eccf531cffc2e562d38bdd879d41e5044ea279af5b73c6a32aabcc8fe04"
)
PINNED_TOKENIZER_CLASS = "transformers.models.qwen2.tokenization_qwen2.Qwen2Tokenizer"
PINNED_BACKEND_CLASS = "tokenizers.Tokenizer"
PINNED_TOKENIZER_FILES: Mapping[str, Mapping[str, int | str]] = MappingProxyType({
    "merges.txt": MappingProxyType({
        "sha256": "599bab54075088774b1733fde865d5bd747cbcc7a547c5bc12610e874e26f5e3",
        "size_bytes": 1_671_839,
    }),
    "tokenizer.json": MappingProxyType({
        "sha256": "aeb13307a71acd8fe81861d94ad54ab689df773318809eed3cbe794b4492dae4",
        "size_bytes": 11_422_654,
    }),
    "tokenizer_config.json": MappingProxyType({
        "sha256": "a62ff0a2472a0fa1b8eaabcb57c59b58afa42a22831dc141400b6e0cf2b65ce3",
        "size_bytes": 9_377,
    }),
    "vocab.json": MappingProxyType({
        "sha256": "ca10d7e9fb3ed18575dd1e277a2579c16d108e32f27439684afa0e10b1440910",
        "size_bytes": 2_776_833,
    }),
})

_TARGET_BANK_CONTEXT = (
    {"role": "system", "content": (
        "This fixed tokenizer qualification context contains no production "
        "candidate, rank, history, or outcome.")},
    {"role": "user", "content": "Acknowledge the tokenizer qualification context."},
    {"role": "assistant", "content": "Acknowledged."},
)


class V13StimulusError(V13SchemaError):
    """A v13 draft fails a tokenizer or mechanical invariant."""


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise V13StimulusError(message)


def sha256_json(value: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def sha256_ints(values: Sequence[int]) -> str:
    canonical_values: list[int] = []
    for value in values:
        _require(isinstance(value, int) and not isinstance(value, bool),
                 "integer-sequence hash input contains a non-integer")
        canonical_values.append(value)
    return hashlib.sha256(
        canonical_json_bytes(canonical_values)).hexdigest()


def _plain_int_sequence(
    values: object,
    label: str,
    *,
    allow_empty: bool = False,
    maximum_exclusive: int | None = None,
) -> list[int]:
    _require(isinstance(values, Sequence)
             and not isinstance(values, (str, bytes)),
             f"{label} is not an integer sequence")
    result = list(values)
    _require(allow_empty or bool(result), f"{label} is empty")
    _require(all(type(value) is int and value >= 0
                 and (maximum_exclusive is None
                      or value < maximum_exclusive)
                 for value in result),
             f"{label} contains a non-plain or out-of-range integer")
    return result


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _installed_version(distribution: str) -> str:
    try:
        return package_version(distribution)
    except PackageNotFoundError as exc:  # pragma: no cover - corrupted env
        raise V13StimulusError(
            f"required tokenizer distribution is absent: {distribution}") from exc


def _tokenizer_snapshot_directory(tokenizer) -> Path:
    init_kwargs = getattr(tokenizer, "init_kwargs", None)
    _require(isinstance(init_kwargs, Mapping),
             "production tokenizer init kwargs are unavailable")
    roots: set[Path] = set()
    for field, filename in (("vocab_file", "vocab.json"),
                            ("merges_file", "merges.txt")):
        raw = init_kwargs.get(field)
        _require(isinstance(raw, str) and raw,
                 f"production tokenizer {field} path is unavailable")
        path = Path(raw).expanduser().absolute()
        _require(path.name == filename and path.is_file(),
                 f"production tokenizer {field} file differs")
        root = path.parent
        _require(root.name == MODEL_REVISION and root.parent.name == "snapshots",
                 f"production tokenizer {field} is not from resolved snapshot "
                 f"{MODEL_REVISION}")
        roots.add(root)
    _require(len(roots) == 1,
             "production tokenizer files resolve to different snapshots")
    root = next(iter(roots))
    init_source = str(init_kwargs.get("name_or_path", ""))
    source_is_model_id = init_source == MODEL_ID
    source_is_snapshot = bool(init_source) and \
        Path(init_source).expanduser().absolute() == root
    _require(source_is_model_id or source_is_snapshot,
             "production tokenizer init source is neither the pinned model ID "
             "nor its exact resolved snapshot")
    return root


def _tokenizer_binding(tokenizer) -> dict[str, Any]:
    tokenizer_class = f"{type(tokenizer).__module__}.{type(tokenizer).__name__}"
    _require(tokenizer_class == PINNED_TOKENIZER_CLASS,
             "production tokenizer wrapper class differs")
    snapshot = _tokenizer_snapshot_directory(tokenizer)
    resolved_revision = snapshot.name
    _require(resolved_revision == MODEL_REVISION,
             "production tokenizer resolved revision differs")
    file_records: dict[str, dict[str, int | str]] = {}
    for filename, expected in PINNED_TOKENIZER_FILES.items():
        path = snapshot / filename
        _require(path.is_file(),
                 f"production tokenizer snapshot file is absent: {filename}")
        size = path.stat().st_size
        digest = _sha256_file(path)
        _require(size == expected["size_bytes"],
                 f"production tokenizer {filename} size differs")
        _require(digest == expected["sha256"],
                 f"production tokenizer {filename} hash differs")
        file_records[filename] = {
            "sha256": digest,
            "size_bytes": size,
        }

    backend = getattr(tokenizer, "backend_tokenizer", None)
    _require(backend is not None and callable(getattr(backend, "to_str", None)),
             "production tokenizer backend serialization is unavailable")
    backend_serialization = backend.to_str()
    _require(isinstance(backend_serialization, str) and backend_serialization,
             "production tokenizer backend serialization is empty")
    backend_class = f"{type(backend).__module__}.{type(backend).__name__}"
    _require(backend_class == PINNED_BACKEND_CLASS,
             "production tokenizer backend class differs")
    backend_sha = hashlib.sha256(
        backend_serialization.encode("utf-8")).hexdigest()
    _require(backend_sha == PINNED_TOKENIZER_BACKEND_SHA256,
             "production tokenizer backend serialization hash differs")

    vocab_sha = sha256_json(tokenizer.get_vocab())
    template = str(getattr(tokenizer, "chat_template", "") or "")
    template_sha = hashlib.sha256(template.encode("utf-8")).hexdigest()
    runtime_source = str(getattr(tokenizer, "name_or_path", ""))
    source_is_model_id = runtime_source == MODEL_ID
    source_is_snapshot = bool(runtime_source) and \
        Path(runtime_source).expanduser().absolute() == snapshot
    _require(source_is_model_id or source_is_snapshot,
             "production tokenizer runtime source differs")
    _require(vocab_sha == PINNED_TOKENIZER_VOCAB_SHA256,
             "production tokenizer vocabulary hash differs")
    _require(template_sha == PINNED_CHAT_TEMPLATE_SHA256,
             "production tokenizer chat-template hash differs")
    _require(type(tokenizer.eos_token_id) is int
             and tokenizer.eos_token_id == 151645,
             "production tokenizer EOS ID differs")
    return {
        "model_id": MODEL_ID,
        "requested_revision": MODEL_REVISION,
        "resolved_snapshot_revision": resolved_revision,
        "tokenizer_class": type(tokenizer).__name__,
        "tokenizer_class_module": type(tokenizer).__module__,
        "backend_class": type(backend).__name__,
        "backend_class_module": type(backend).__module__,
        "backend_serialization_utf8_bytes": len(
            backend_serialization.encode("utf-8")),
        "backend_serialization_sha256": backend_sha,
        "snapshot_files": file_records,
        "snapshot_files_sha256": sha256_json(file_records),
        "vocabulary_sha256": vocab_sha,
        "chat_template_sha256": template_sha,
        "eos_token": str(tokenizer.eos_token),
        "eos_token_id": tokenizer.eos_token_id,
        "transformers_version": _installed_version("transformers"),
        "tokenizers_version": _installed_version("tokenizers"),
        "huggingface_hub_version": _installed_version("huggingface-hub"),
    }


def carrier_attempt_spec(
    fixture: Mapping[str, Any],
    *,
    render_index: int,
    attempt_index: int,
) -> dict[str, Any]:
    """Return the exact Section-5 prompt, sampler, cap, digest, and seed.

    Render and attempt indices are deliberately one-based: the two render
    streams are 1..2 and their only allowed sequential attempts are 1..3.
    Neither index is a permutation rank or an input to candidate eligibility.
    """

    validate_fixture_schema(fixture)
    _require(type(render_index) is int and
             render_index in CARRIER_RENDER_INDICES,
             "carrier render index must be one of 1,2")
    _require(type(attempt_index) is int and
             attempt_index in CARRIER_ATTEMPT_INDICES,
             "carrier attempt index must be one of 1,2,3")
    stable_id = fixture.get("stable_candidate_id")
    _require(isinstance(stable_id, str) and
             re.fullmatch(r"[0-9a-f]{64}", stable_id) is not None,
             "carrier stable candidate ID is not lowercase SHA-256")
    digest_input = [DESIGN_ID, stable_id, render_index, attempt_index]
    digest_bytes = hashlib.sha256(canonical_json_bytes(digest_input)).digest()
    digest_hex = digest_bytes.hex()
    generator_seed = int.from_bytes(
        digest_bytes[:8], byteorder="big", signed=False) & ((1 << 63) - 1)
    _require(0 <= generator_seed < (1 << 63),
             "carrier attempt seed is not a nonnegative 63-bit integer")
    core = {
        "schema": CARRIER_ATTEMPT_SCHEMA,
        "design_id": DESIGN_ID,
        "stable_candidate_id": stable_id,
        "render_index": render_index,
        "render_count": len(CARRIER_RENDER_INDICES),
        "attempt_index": attempt_index,
        "max_attempts_per_render": CARRIER_MAX_ATTEMPTS_PER_RENDER,
        "attempt_digest_input": digest_input,
        "attempt_digest_sha256": digest_hex,
        "torch_generator_seed": generator_seed,
        "torch_generator_device": "cpu",
        "prompt": CARRIER_REQUEST,
        "q_call_width": CARRIER_Q_CALL_WIDTH,
        "sampling": True,
        "temperature": CARRIER_TEMPERATURE,
        "top_p": CARRIER_TOP_P,
        "top_k": CARRIER_TOP_K,
        "top_k_disabled": True,
        "content_token_cap": CARRIER_CONTENT_TOKEN_CAP,
        "content_ids_exclude_terminal_eos": True,
        "terminal_eos_witness_calls": 1,
        "maximum_sampling_calls_including_eos": CARRIER_MAX_SAMPLING_CALLS,
        "normal_eos_required": True,
    }
    return {**core, "attempt_spec_sha256": sha256_json(core)}


def _validated_attempt_spec(
    fixture: Mapping[str, Any],
    attempt_spec: Mapping[str, Any],
) -> dict[str, Any]:
    _require(isinstance(attempt_spec, Mapping),
             "carrier attempt spec is missing")
    render_index = attempt_spec.get("render_index")
    attempt_index = attempt_spec.get("attempt_index")
    expected = carrier_attempt_spec(
        fixture,
        render_index=render_index,
        attempt_index=attempt_index,
    )
    supplied = dict(attempt_spec)
    _require(supplied == expected,
             "carrier attempt prompt, sampler, digest, seed, or cap differs "
             "from frozen Section 5")
    return expected


def _special_literals(tokenizer) -> tuple[str, ...]:
    values = set(str(value) for value in tokenizer.all_special_tokens)
    # Qwen has reserved/control literals in the added vocabulary that are not
    # all marked special by transformers.  They are still unsafe authored text.
    values.update(
        str(value) for value in tokenizer.get_added_vocab()
        if str(value).startswith("<") and str(value).endswith(">")
    )
    return tuple(sorted((value for value in values if value),
                        key=lambda value: (len(value), value)))


def _validate_no_special_literals(tokenizer, text: str, label: str) -> None:
    for literal in _special_literals(tokenizer):
        _require(literal not in text,
                 f"{label} contains tokenizer control literal {literal!r}")


def _canonical_evidence(tokenizer, messages: list[dict[str, str]],
                        label: str) -> tuple[dict[str, Any], list[int], list[int]]:
    ids = _plain_int_sequence(
        canonical_ids_any(tokenizer, messages, render_hf),
        f"{label} canonical token IDs",
        maximum_exclusive=len(tokenizer),
    )
    decoded = tokenizer.decode(
        ids, skip_special_tokens=False, clean_up_tokenization_spaces=False)
    decoded_ids = _plain_int_sequence(
        tokenizer.encode(decoded, add_special_tokens=False),
        f"{label} re-encoded token IDs",
        maximum_exclusive=len(tokenizer),
    )
    _require(decoded_ids == ids, f"{label} canonical stream does not round-trip")
    starts = message_starts(tokenizer, ids)
    _require(len(starts) == len(messages) and starts[0] == 0,
             f"{label} canonical message-start coverage differs")
    widths = [
        (starts[index + 1] if index + 1 < len(starts) else len(ids)) - start
        for index, start in enumerate(starts)
    ]
    content_widths = []
    for index, message in enumerate(messages):
        content = str(message.get("content", ""))
        _validate_no_special_literals(tokenizer, content,
                                      f"{label} message {index}")
        content_ids = _plain_int_sequence(
            tokenizer.encode(content, add_special_tokens=False),
            f"{label} message {index} content token IDs",
            maximum_exclusive=len(tokenizer),
        )
        _require(content_ids, f"{label} message {index} has no content tokens")
        _require(len(content_ids) <= MAX_PREFILL_CALL_TOKENS,
                 f"{label} message {index} exceeds 4096 content tokens")
        content_widths.append(len(content_ids))
    return ({
        "canonical_token_count": len(ids),
        "canonical_token_ids_sha256": sha256_ints(ids),
        "decoded_utf8_sha256": hashlib.sha256(
            decoded.encode("utf-8")).hexdigest(),
        "literal_messages_sha256": sha256_json(messages),
        "message_start_positions": starts,
        "message_start_positions_sha256": sha256_ints(starts),
        "canonical_message_widths": widths,
        "content_token_widths": content_widths,
        "decoded_round_trip": True,
    }, ids, starts)


def _event_evidence(plan: ReplayPlan | FreshDestinationPlan,
                    label: str) -> dict[str, Any]:
    events = plan.events
    _require(events, f"{label} has no replay events")
    _require(all(1 <= event.width <= MAX_PREFILL_CALL_TOKENS
                 for event in events),
             f"{label} has a call wider than 4096 tokens")
    _require(all(event.width == 1 for event in events if event.kind == "q1"),
             f"{label} has a non-unit q1 call")
    return {
        "event_count": len(events),
        "max_call_width": max(event.width for event in events),
        "q1_call_count": sum(event.kind == "q1" for event in events),
        "events_sha256": sha256_json([asdict(event) for event in events]),
        "geometry_sha256": sha256_json(plan.geometry()),
    }


_SMALL_NUMBERS = (
    "zero", "one", "two", "three", "four", "five", "six", "seven",
    "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen",
    "fifteen", "sixteen", "seventeen", "eighteen", "nineteen",
)
_TENS = {
    20: "twenty", 30: "thirty", 40: "forty", 50: "fifty",
    60: "sixty", 70: "seventy", 80: "eighty", 90: "ninety",
}


def _integer_words(value: int, *, use_and: bool = False) -> str:
    """Deterministic English rendering for the recipe's bounded integers."""

    if value < 0:
        return "minus " + _integer_words(-value, use_and=use_and)
    if value < 20:
        return _SMALL_NUMBERS[value]
    if value < 100:
        tens, remainder = divmod(value, 10)
        return _TENS[tens * 10] + (
            "-" + _SMALL_NUMBERS[remainder] if remainder else "")
    if value < 1000:
        hundreds, remainder = divmod(value, 100)
        suffix = " and " if use_and and remainder else " "
        return (_SMALL_NUMBERS[hundreds] + " hundred" +
                (suffix + _integer_words(remainder, use_and=use_and)
                 if remainder else ""))
    for scale, word in ((1_000_000_000, "billion"),
                        (1_000_000, "million"), (1000, "thousand")):
        if value >= scale:
            leading, remainder = divmod(value, scale)
            suffix = " and " if use_and and remainder < 100 else " "
            return (_integer_words(leading, use_and=use_and) + f" {word}" +
                    (suffix + _integer_words(remainder, use_and=use_and)
                     if remainder else ""))
    raise AssertionError("unreachable integer word rendering")


def _numeric_forms(value: int | float) -> set[str]:
    _require(not isinstance(value, bool), "boolean entered numeric inventory")
    numeric = float(value)
    _require(math.isfinite(numeric), "nonfinite carrier-forbidden numeric")
    forms: set[str] = set()
    if numeric.is_integer():
        integer = int(numeric)
        forms.update({str(integer), f"{integer:,}",
                      _integer_words(integer, use_and=False),
                      _integer_words(integer, use_and=True)})
    else:
        rendered = format(numeric, ".15g")
        forms.add(rendered)
        whole, fraction = rendered.split(".", 1)
        word = _integer_words(int(whole), use_and=False)
        forms.add(word + " point " + " ".join(
            _SMALL_NUMBERS[int(digit)] for digit in fraction))
    return {value for value in forms if value}


_TIME_RE = re.compile(r"^(?P<hour>[0-2][0-9]):(?P<minute>[0-5][0-9])$")


def _time_forms(value: str) -> set[str]:
    match = _TIME_RE.fullmatch(value)
    _require(match is not None, f"recorded time has invalid form: {value!r}")
    hour = int(match.group("hour"))
    minute = int(match.group("minute"))
    _require(hour < 24, f"recorded time has invalid hour: {value!r}")
    hour12 = hour % 12 or 12
    suffix = "am" if hour < 12 else "pm"
    if minute == 0:
        minute_words = "o'clock"
        spoken12 = _integer_words(hour12)
        spoken24 = _integer_words(hour) + " hundred"
    elif minute < 10:
        minute_words = "oh " + _integer_words(minute)
        spoken12 = _integer_words(hour12) + " " + minute_words
        spoken24 = _integer_words(hour) + " " + minute_words
    else:
        minute_words = _integer_words(minute)
        spoken12 = _integer_words(hour12) + " " + minute_words
        spoken24 = _integer_words(hour) + " " + minute_words
    return {
        value,
        f"{hour}:{minute:02d}",
        f"{hour:02d}{minute:02d}",
        f"{hour}.{minute:02d}",
        f"{spoken12} {suffix}",
        f"{spoken12} {suffix[0]}.{suffix[1]}.",
        spoken24,
        (_integer_words(hour12) + " " + minute_words
         if minute == 0 else spoken12),
    }


_SEPARATOR_RE = re.compile(r"[\s\-\u2010-\u2015_/:.]+")
_SURFACE_JOINERS = (" ", "-", "/", "_", ":", ".", "\u2013", "\u2014", "")


def _surface_components(value: str) -> list[str]:
    components: list[str] = []
    current: list[str] = []
    for character in value:
        category = unicodedata.category(character)
        if character.isalnum() or category.startswith("M"):
            current.append(character)
        elif current:
            components.append("".join(current))
            current = []
    if current:
        components.append("".join(current))
    return components


def _replace_unicode_separators(value: str, replacement: str) -> str:
    output: list[str] = []
    in_separator = False
    for character in value:
        category = unicodedata.category(character)
        separator = (character.isspace() or character == "_" or
                     category.startswith("P") or category.startswith("Z"))
        if separator:
            if not in_separator and replacement:
                output.append(replacement)
            in_separator = True
        else:
            output.append(character)
            in_separator = False
    return "".join(output).strip(replacement or None)


def _surface_variants(value: str) -> set[str]:
    """Expand Unicode/case plus punctuation, slash, camel, and split letters."""

    value = str(value).strip()
    if not value:
        return set()
    normalized = {
        unicodedata.normalize(mode, value)
        for mode in ("NFC", "NFD", "NFKC", "NFKD")
    }
    cased = set()
    for item in normalized:
        cased.update({item, item.casefold(), item.lower(), item.upper()})
    expanded = set(cased)
    for item in tuple(cased):
        for replacement in _SURFACE_JOINERS:
            candidate = _SEPARATOR_RE.sub(replacement, item).strip()
            if candidate:
                expanded.add(candidate)
            unicode_candidate = _replace_unicode_separators(item, replacement)
            if unicode_candidate:
                expanded.add(unicode_candidate)
        components = _surface_components(item)
        if len(components) > 1:
            for joiner in _SURFACE_JOINERS:
                joined = joiner.join(components)
                if joined:
                    expanded.add(joined)
            # Explicit camel forms bind the intended no-separator variants,
            # rather than relying only on casefolding an ordinary join.
            expanded.add(components[0].lower() + "".join(
                component[:1].upper() + component[1:].lower()
                for component in components[1:]))
            expanded.add("".join(
                component[:1].upper() + component[1:].lower()
                for component in components))
        elif (len(components) == 1 and components[0] == item and
              2 <= len(item) <= 32 and all(character.isalpha()
                                            for character in item)):
            # This closes the Q.u.a.r.t.z / s-i-x-t-y class without an
            # unbounded combinatorial punctuation expansion.
            for joiner in _SURFACE_JOINERS[:-1]:
                expanded.add(joiner.join(item))
    return {item for item in expanded if item}


def _normalized_surface(value: str) -> str:
    value = unicodedata.normalize("NFKC", value).casefold()
    return re.sub(r"\s+", " ", value).strip()


def _is_surface_alphanumeric(character: str) -> bool:
    # Unicode Lm contains punctuation-like modifier letters such as U+02BC
    # MODIFIER LETTER APOSTROPHE.  Treating those as semantic letters creates
    # a separator bypass (Qʼuʼaʼrʼtʼz), so only ordinary letter/number classes
    # participate in surface skeletons and their word boundaries.
    return unicodedata.category(character) in {
        "Lu", "Ll", "Lt", "Lo", "Nd", "Nl", "No",
    }


def _surface_skeleton(value: str) -> str:
    """Return alphanumerics after compatibility/case/mark normalization."""

    normalized = unicodedata.normalize("NFKD", value).casefold()
    return "".join(character for character in normalized
                   if _is_surface_alphanumeric(character))


def _contains_separator_insensitive_skeleton(text: str, skeleton: str) -> bool:
    """Match a bounded literal while ignoring arbitrary non-alphanumerics.

    This closes finite-enumeration gaps such as bullets, zero-width format
    characters, combining marks, apostrophes, and mixed punctuation inserted
    between the characters of a forbidden word or phrase.  Adjacent
    alphanumerics still enforce literal word boundaries, so ``Quartzite`` does
    not become the bounded target ``Quartz``.
    """

    _require(isinstance(skeleton, str) and bool(skeleton)
             and all(_is_surface_alphanumeric(character)
                     for character in skeleton),
             "forbidden surface skeleton is invalid")
    normalized = unicodedata.normalize("NFKD", text).casefold()
    for start, character in enumerate(normalized):
        if character != skeleton[0]:
            continue
        if start > 0 and _is_surface_alphanumeric(normalized[start - 1]):
            continue
        cursor = start
        matched = True
        for wanted in skeleton[1:]:
            cursor += 1
            while (cursor < len(normalized)
                   and not _is_surface_alphanumeric(normalized[cursor])):
                cursor += 1
            if cursor >= len(normalized) or normalized[cursor] != wanted:
                matched = False
                break
        if matched and (cursor + 1 == len(normalized)
                        or not _is_surface_alphanumeric(
                            normalized[cursor + 1])):
            return True
    return False


def _case_declared_forbidden_phrases(
    fixture: Mapping[str, Any],
) -> list[str]:
    raw = fixture.get("case_declared_forbidden_phrases", [])
    _require(isinstance(raw, list),
             "case-declared forbidden phrases must be a JSON list")
    phrases: list[str] = []
    normalized_seen: set[str] = set()
    for index, value in enumerate(raw):
        _require(isinstance(value, str) and value and value == value.strip(),
                 f"case-declared forbidden phrase {index} is not a nonempty "
                 "trimmed string")
        normalized = _normalized_surface(value)
        _require(normalized and normalized not in normalized_seen,
                 "case-declared forbidden phrases are empty or duplicate "
                 "under Unicode casefolding")
        normalized_seen.add(normalized)
        phrases.append(value)
    return phrases


def expand_carrier_forbidden_surfaces(tokenizer, fixture: Mapping[str, Any]) -> dict[str, Any]:
    """Deterministically expand the recipe's pre-carrier semantic inventory."""

    _tokenizer_binding(tokenizer)
    validate_fixture_schema(fixture)
    inventory = fixture.get("carrier_forbidden_inventory")
    _require(isinstance(inventory, Mapping), "carrier-forbidden inventory missing")
    base_forms = {str(value) for value in inventory.get(
        "exact_forbidden_forms", []) if str(value)}
    nonfocal_fact_name = inventory.get("nonfocal", {}).get("fact_name")
    _require(isinstance(nonfocal_fact_name, str) and nonfocal_fact_name,
             "plain nonfocal fact name is missing")
    base_forms.add(nonfocal_fact_name)
    declared_phrases = _case_declared_forbidden_phrases(fixture)
    base_forms.update(declared_phrases)
    numerics = list(inventory.get("rule_semantics", {}).get(
        "numeric_values", []))
    recorded_times = [str(value) for value in inventory.get(
        "rule_semantics", {}).get("time_forms", [])]

    numeric_inventory: dict[str, list[str]] = {}
    for numeric in numerics:
        forms = _numeric_forms(numeric)
        numeric_inventory[str(numeric)] = sorted(forms)
        base_forms.update(forms)
    time_inventory: dict[str, list[str]] = {}
    for recorded_time in recorded_times:
        forms = _time_forms(recorded_time)
        time_inventory[recorded_time] = sorted(forms)
        base_forms.update(forms)

    raw_surface_forms: set[str] = set()
    for form in base_forms:
        raw_surface_forms.update(_surface_variants(form))
    normalized_forms = sorted(
        {_normalized_surface(form) for form in raw_surface_forms
         if _normalized_surface(form)},
        key=lambda value: (-len(value), value),
    )
    skeleton_sources: dict[str, str] = {}
    for form in sorted(base_forms):
        skeleton = _surface_skeleton(form)
        if skeleton and (skeleton not in skeleton_sources
                         or form < skeleton_sources[skeleton]):
            skeleton_sources[skeleton] = form
    skeleton_records = [
        {"skeleton": skeleton, "surface": skeleton_sources[skeleton]}
        for skeleton in sorted(skeleton_sources, key=lambda value: (-len(value), value))
    ]

    special_ids = set(_plain_int_sequence(
        tokenizer.all_special_ids,
        "production tokenizer special IDs",
        maximum_exclusive=len(tokenizer),
    ))
    _require(len(raw_surface_forms) <= 4096
             and all(len(form.encode("utf-8")) <= 512
                     for form in raw_surface_forms),
             "forbidden surface expansion exceeds frozen batching bounds")
    _require(len(base_forms) <= 1024,
             "forbidden semantic base inventory exceeds frozen batching bound")
    token_inputs = [
        (form, token_surface)
        for form in sorted(base_forms)
        for token_surface in (form, " " + form)
    ]
    encoded_batch = tokenizer(
        [token_surface for _form, token_surface in token_inputs],
        add_special_tokens=False,
        padding=False,
        truncation=False,
        return_attention_mask=False,
        return_token_type_ids=False,
    )
    _require(isinstance(encoded_batch, Mapping)
             and set(encoded_batch) == {"input_ids"},
             "forbidden surface tokenizer batch fields differ")
    encoded_rows = encoded_batch["input_ids"]
    _require(isinstance(encoded_rows, Sequence)
             and len(encoded_rows) == len(token_inputs),
             "forbidden surface tokenizer batch width differs")
    token_record_by_ids: dict[tuple[int, ...], str] = {}
    for (form, _token_surface), raw_ids in zip(token_inputs, encoded_rows):
        # Both forms are needed for Qwen BPE: a word at the beginning of text
        # and the same word following whitespace can have different first IDs.
        ids = tuple(_plain_int_sequence(
            raw_ids,
            "forbidden surface token IDs",
            allow_empty=True,
            maximum_exclusive=len(tokenizer),
        ))
        if not ids or any(value in special_ids for value in ids):
            continue
        previous = token_record_by_ids.get(ids)
        if previous is None or form < previous:
            token_record_by_ids[ids] = form
    token_records = [
        {"ids": list(ids), "surface": token_record_by_ids[ids]}
        for ids in sorted(token_record_by_ids)
    ]

    core = {
        "schema": FORBIDDEN_SURFACE_SCHEMA,
        "design_id": DESIGN_ID,
        "stable_candidate_id": fixture.get("stable_candidate_id"),
        "semantic_inventory_sha256": inventory.get(
            "semantic_inventory_sha256"),
        "case_declared_forbidden_phrases": declared_phrases,
        "case_declared_forbidden_phrases_sha256": sha256_json(
            declared_phrases),
        "case_declared_forbidden_phrase_count": len(declared_phrases),
        "plain_nonfocal_fact_name": nonfocal_fact_name,
        "tokenizer_vocabulary_sha256": PINNED_TOKENIZER_VOCAB_SHA256,
        "tokenizer_backend_serialization_sha256":
            PINNED_TOKENIZER_BACKEND_SHA256,
        "unicode_normalization_modes": ["NFC", "NFD", "NFKC", "NFKD"],
        "casefold_applied": True,
        "separator_insensitive_matching_applied": True,
        "production_token_subsequences_use_semantic_base_forms": True,
        "punctuation_hyphen_space_expansion_applied": True,
        "slash_camel_split_letter_expansion_applied": True,
        "plain_nonfocal_fact_name_included": True,
        "all_recorded_numerics_expanded": True,
        "all_recorded_times_expanded": True,
        "numeric_form_inventory": numeric_inventory,
        "time_form_inventory": time_inventory,
        "base_forms": sorted(base_forms),
        "raw_surface_forms": sorted(raw_surface_forms),
        "normalized_surface_forms": normalized_forms,
        "separator_insensitive_surfaces": skeleton_records,
        "production_token_subsequences": token_records,
    }
    return {**core, "expansion_sha256": sha256_json(core)}


def _contains_bounded_surface(text: str, surface: str) -> bool:
    start = 0
    while True:
        index = text.find(surface, start)
        if index < 0:
            return False
        end = index + len(surface)
        left_ok = (not surface[0].isalnum() or index == 0 or
                   not text[index - 1].isalnum())
        right_ok = (not surface[-1].isalnum() or end == len(text) or
                    not text[end].isalnum())
        if left_ok and right_ok:
            return True
        start = index + 1


def _find_subsequence(container: Sequence[int], needle: Sequence[int]) -> int | None:
    width = len(needle)
    if width == 0 or width > len(container):
        return None
    wanted = list(needle)
    for index in range(len(container) - width + 1):
        if list(container[index:index + width]) == wanted:
            return index
    return None


def validate_carrier_attempt(
    tokenizer,
    fixture: Mapping[str, Any],
    carrier_content: str,
    *,
    attempt_spec: Mapping[str, Any],
    generated_content_ids: Sequence[int],
    termination_token_id: int | None,
    hit_token_cap: bool,
    max_new_tokens: int = CARRIER_MAX_NEW_TOKENS,
) -> dict[str, Any]:
    """Pure mechanical acceptance gate for one already-generated carrier.

    The function never imports or invokes a subject model.  It rejects an
    attempt unless the supplied production content IDs decode exactly to the
    supplied text and an explicit EOS follows before the generation cap.
    Target-aware semantic review remains a separate required Phase-A action.
    """

    binding = _tokenizer_binding(tokenizer)
    frozen_attempt = _validated_attempt_spec(fixture, attempt_spec)
    _require(isinstance(carrier_content, str) and carrier_content.strip(),
             "carrier content is empty")
    _validate_no_special_literals(tokenizer, carrier_content, "carrier")
    _require(not any(character.isdigit() for character in carrier_content),
             "carrier contains a Unicode digit")
    word_count = len(carrier_content.split())
    _require(CARRIER_WORD_BOUNDS[0] <= word_count <= CARRIER_WORD_BOUNDS[1],
             f"carrier word count {word_count} is outside 40..60")

    ids = _plain_int_sequence(
        generated_content_ids,
        "carrier generated-content token IDs",
        maximum_exclusive=len(tokenizer),
    )
    _require(all(value not in set(tokenizer.all_special_ids) for value in ids),
             "carrier content contains a special token ID")
    _require(CARRIER_TOKEN_BOUNDS[0] <= len(ids) <= CARRIER_TOKEN_BOUNDS[1],
             f"carrier token count {len(ids)} is outside 40..80")
    _require(type(max_new_tokens) is int and
             max_new_tokens == CARRIER_CONTENT_TOKEN_CAP,
             "carrier content-token cap differs from frozen 80")
    _require(hit_token_cap is False,
             "carrier generation hit the token cap or omitted a false cap flag")
    _require(type(termination_token_id) is int
             and termination_token_id == tokenizer.eos_token_id,
             "carrier generation did not terminate with EOS")
    _require(len(ids) + 1 <= CARRIER_MAX_SAMPLING_CALLS,
             "carrier content plus EOS exceeds the frozen sampling-call cap")
    decoded = tokenizer.decode(
        ids, skip_special_tokens=False, clean_up_tokenization_spaces=False)
    _require(decoded == carrier_content,
             "carrier generated-content IDs do not decode exactly to text")
    reencoded = _plain_int_sequence(
        tokenizer.encode(decoded, add_special_tokens=False),
        "carrier re-encoded content token IDs",
        maximum_exclusive=len(tokenizer),
    )
    _require(reencoded == ids,
             "carrier encode(decode(ids)) does not reproduce exact content IDs")

    expansion = expand_carrier_forbidden_surfaces(tokenizer, fixture)
    normalized_text = _normalized_surface(carrier_content)
    for surface in expansion["normalized_surface_forms"]:
        if _contains_bounded_surface(normalized_text, surface):
            raise V13StimulusError(
                f"carrier leaks forbidden normalized surface {surface!r}")
    for record in expansion["separator_insensitive_surfaces"]:
        if _contains_separator_insensitive_skeleton(
                carrier_content, record["skeleton"]):
            raise V13StimulusError(
                "carrier leaks forbidden separator-insensitive surface "
                f"{record['surface']!r}")
    for record in expansion["production_token_subsequences"]:
        index = _find_subsequence(ids, record["ids"])
        if index is not None:
            raise V13StimulusError(
                "carrier leaks forbidden production-token subsequence "
                f"for {record['surface']!r} at content token {index}")

    return {
        "status": "MECHANICAL_CARRIER_PASS_SEMANTIC_REVIEW_PENDING",
        "execution_ready": False,
        "subject_model_called_by_validator": False,
        "target_aware_semantic_review": "PENDING_REQUIRED",
        "word_count": word_count,
        "production_content_token_count": len(ids),
        "sampling_call_count_including_eos": len(ids) + 1,
        "content_token_ids_sha256": sha256_ints(ids),
        "content_utf8_sha256": hashlib.sha256(
            carrier_content.encode("utf-8")).hexdigest(),
        "decoded_text_exact": True,
        "encode_decode_ids_exact": True,
        "decoded_round_trip": True,
        "termination_token_id": termination_token_id,
        "terminated_with_eos": True,
        "content_ids_exclude_terminal_eos": True,
        "hit_token_cap": False,
        "max_new_tokens": max_new_tokens,
        "content_token_cap": CARRIER_CONTENT_TOKEN_CAP,
        "maximum_sampling_calls_including_eos": CARRIER_MAX_SAMPLING_CALLS,
        "attempt_spec": frozen_attempt,
        "attempt_spec_sha256": frozen_attempt["attempt_spec_sha256"],
        "forbidden_surface_expansion_sha256": expansion["expansion_sha256"],
        "case_declared_forbidden_phrases_sha256": expansion[
            "case_declared_forbidden_phrases_sha256"],
        "case_declared_forbidden_phrase_count": expansion[
            "case_declared_forbidden_phrase_count"],
        "forbidden_normalized_surface_count": len(
            expansion["normalized_surface_forms"]),
        "forbidden_token_subsequence_count": len(
            expansion["production_token_subsequences"]),
        "tokenizer_binding_sha256": sha256_json(binding),
    }


def _exact_pair_checks(fixture: Mapping[str, Any]) -> tuple[
        list[dict[str, str]], list[dict[str, str]], int, list[int]]:
    validate_fixture_schema(fixture)
    _require(fixture.get("pool_member") is False,
             "tokenizer sentinel unexpectedly belongs to production pool")
    authorization = fixture.get("materialization_authorization", {})
    development_status = "OUT_OF_POOL_DEVELOPMENT_SENTINEL"
    _require(authorization.get("kind") == development_status,
             "tokenizer sentinel has non-development authorization")
    _require(authorization.get("status") == development_status,
             "tokenizer sentinel has non-development authorization status")
    _require(set(authorization) == {
        "kind", "status", "candidate_id", "permutation_rank",
        "seed_manifest_sha256", "seed_git_commit",
        "literal_permutation_sha256", "literal_git_commit",
    }, "tokenizer sentinel authorization fields differ")
    _require(all(authorization.get(key) is None for key in (
        "candidate_id",
        "permutation_rank", "seed_manifest_sha256", "seed_git_commit",
        "literal_permutation_sha256", "literal_git_commit")),
        "tokenizer sentinel carries rank/seed/permutation state")
    correct = fixture["variants"]["C"]["messages"]
    wrong = fixture["variants"]["W"]["messages"]
    _require(len(correct) == len(wrong) == 9, "C/W message counts differ")
    expected_roles = ["system"] + [
        "user" if index % 2 else "assistant" for index in range(1, 9)]
    _require([item.get("role") for item in correct] == expected_roles and
             [item.get("role") for item in wrong] == expected_roles,
             "C/W role sequences differ")
    middle = int(fixture.get("middle_end_msg", -1))
    _require(middle == 7, "sentinel retained-tail boundary differs")
    allowlist = _plain_int_sequence(
        fixture.get("changed_message_allowlist", []),
        "changed-message allowlist",
        maximum_exclusive=len(correct),
    )
    changed = [index for index, (left, right) in enumerate(zip(correct, wrong))
               if left != right]
    _require(allowlist == [3, 6] and changed == allowlist,
             "C/W exact changed-message allowlist differs")
    _require(correct[0] == wrong[0], "C/W system messages differ")
    _require(correct[middle:] == wrong[middle:],
             "C/W retained tails are not byte-identical")
    return correct, wrong, middle, allowlist


def _variant_plans(tokenizer, messages: list[dict[str, str]], *,
                   middle: int, carrier_content: str, label: str) -> dict[str, Any]:
    history_evidence, _, _ = _canonical_evidence(
        tokenizer, messages, f"{label} history")
    completed = complete_source_messages(
        messages, middle_end_msg=middle, carrier_content=carrier_content)
    completed_evidence, completed_ids, completed_starts = _canonical_evidence(
        tokenizer, completed, f"{label} completed source")
    native = build_role_native_plan(
        tokenizer, messages, middle_end_msg=middle,
        carrier_content=carrier_content)
    turn = build_turn_aligned_plan(
        tokenizer, messages, middle_end_msg=middle,
        carrier_content=carrier_content)
    fresh = build_fresh_destination_plan(
        tokenizer, messages, middle_end_msg=middle,
        carrier_content=carrier_content)
    _require(native.token_ids == completed_ids,
             f"{label} N plan differs from canonical completed source")
    _require(native.message_start_positions == completed_starts,
             f"{label} N message starts differ")
    _require(native.token_ids == turn.token_ids and
             native.message_start_positions == turn.message_start_positions and
             native.regions == turn.regions,
             f"{label} N/P token stream, starts, or carrier regions differ")
    noncarrier_count = source_noncarrier_token_count(native)
    _require(NONCARRIER_TOKEN_BOUNDS[0] <= noncarrier_count <=
             NONCARRIER_TOKEN_BOUNDS[1],
             f"{label} noncarrier skeleton {noncarrier_count} outside 940..1180")
    _require(COMPLETED_SOURCE_TOKEN_BOUNDS[0] <= len(native.token_ids) <=
             COMPLETED_SOURCE_TOKEN_BOUNDS[1],
             f"{label} completed source {len(native.token_ids)} outside 900..1400")
    _require(native.regions.anchor_content_end < len(native.token_ids),
             f"{label} R3 reaches the completed source end")
    return {
        "messages": messages,
        "completed_messages": completed,
        "history": history_evidence,
        "completed": completed_evidence,
        "native": native,
        "turn": turn,
        "fresh": fresh,
        "noncarrier_token_count": noncarrier_count,
        "native_events": _event_evidence(native, f"{label} N"),
        "turn_events": _event_evidence(turn, f"{label} P"),
        "fresh_events": _event_evidence(fresh, f"{label} F"),
    }


def _nonprefix_ids(left: Sequence[int], right: Sequence[int]) -> bool:
    a, b = list(left), list(right)
    return bool(a and b and a != b and a[:len(b)] != b and b[:len(a)] != a)


def _probe_evidence(tokenizer, context_messages: list[dict[str, str]],
                    probe: str, targets: tuple[str, str], label: str) -> dict[str, Any]:
    _validate_no_special_literals(tokenizer, probe, f"{label} probe")
    _require(len(tokenizer.encode(probe, add_special_tokens=False)) <=
             MAX_PREFILL_CALL_TOKENS,
             f"{label} probe exceeds 4096 tokens")
    source_ids = _plain_int_sequence(
        canonical_ids_any(tokenizer, context_messages, render_hf),
        f"{label} source token IDs",
        maximum_exclusive=len(tokenizer),
    )
    prefix = build_probe_generation_prefix(tokenizer, context_messages, probe)
    _require(prefix[:len(source_ids)] == source_ids and len(prefix) > len(source_ids),
             f"{label} probe prefix is not a strict source extension")
    starts = message_starts(tokenizer, prefix)
    _require(len(starts) == len(context_messages) + 2,
             f"{label} probe/header message-start coverage differs")
    probe_start = starts[len(context_messages)]
    header_start = starts[len(context_messages) + 1]
    answer_position = len(prefix)
    _require(probe_start == len(source_ids) < header_start < answer_position,
             f"{label} source/probe/header/answer positions differ")

    target_rows = []
    target_id_rows = []
    for target in targets:
        _validate_no_special_literals(tokenizer, target, f"{label} target")
        ids = _plain_int_sequence(
            probe_target_ids(tokenizer, context_messages, probe, target),
            f"{label} target token IDs",
            maximum_exclusive=len(tokenizer),
        )
        _require(1 <= len(ids) <= 4,
                 f"{label} target {target!r} is outside 1..4 answer tokens")
        _require(all(value not in set(tokenizer.all_special_ids) for value in ids),
                 f"{label} target {target!r} includes a special token")
        decoded_target = tokenizer.decode(
            ids, skip_special_tokens=False,
            clean_up_tokenization_spaces=False)
        _require(decoded_target == target,
                 f"{label} target IDs do not decode to exact target text")
        reencoded_target = _plain_int_sequence(
            tokenizer.encode(decoded_target, add_special_tokens=False),
            f"{label} re-encoded target token IDs",
            maximum_exclusive=len(tokenizer),
        )
        _require(reencoded_target == ids,
                 f"{label} target encode(decode(ids)) differs")
        full = _plain_int_sequence(
            canonical_ids_any(
                tokenizer,
                context_messages + [
                    {"role": "user", "content": probe},
                    {"role": "assistant", "content": target},
                ],
                render_hf,
            ),
            f"{label} full target render token IDs",
            maximum_exclusive=len(tokenizer),
        )
        target_end = answer_position + len(ids)
        _require(full[:answer_position] == prefix,
                 f"{label} target render changed the answer header")
        _require(full[answer_position:target_end] == ids,
                 f"{label} target does not begin at the answer position")
        _require(target_end < len(full) and
                 full[target_end] == tokenizer.eos_token_id,
                 f"{label} target is not followed by the assistant close")
        target_rows.append({
            "text": target,
            "token_count": len(ids),
            "token_ids": ids,
            "token_ids_sha256": sha256_ints(ids),
            "decoded_text_exact": True,
            "encode_decode_ids_exact": True,
            "target_start": answer_position,
            "target_end": target_end,
            "assistant_close_position": target_end,
        })
        target_id_rows.append(ids)
    _require(abs(len(target_id_rows[0]) - len(target_id_rows[1])) <= 1,
             f"{label} target token lengths differ by more than one")
    _require(_nonprefix_ids(target_id_rows[0], target_id_rows[1]),
             f"{label} target token IDs are equal or prefixing")
    folded = [unicodedata.normalize("NFKC", value).casefold()
              for value in targets]
    _require(folded[0] != folded[1] and
             not folded[0].startswith(folded[1]) and
             not folded[1].startswith(folded[0]),
             f"{label} target strings are equal or prefixing")
    return {
        "source_token_count": len(source_ids),
        "source_token_ids_sha256": sha256_ints(source_ids),
        "probe_utf8_sha256": hashlib.sha256(probe.encode("utf-8")).hexdigest(),
        "probe_message_start": probe_start,
        "assistant_header_start": header_start,
        "answer_position": answer_position,
        "generation_prefix_token_count": len(prefix),
        "generation_prefix_sha256": sha256_ints(prefix),
        "targets": target_rows,
        "target_ids_distinct_nonprefix": True,
        "target_length_difference": abs(
            len(target_id_rows[0]) - len(target_id_rows[1])),
    }


def validate_production_target_banks(tokenizer) -> dict[str, Any]:
    """Qualify all 8 focal and 4 nonfocal component banks without a tuple.

    This reads only the compact recipe definition.  It neither constructs nor
    inspects any production candidate, permutation seed, rank, or history.
    Exact contextual assistant-content IDs are persisted, not merely a PASS
    label, so later manifests can bind this qualification byte-for-byte.
    """

    binding = _tokenizer_binding(tokenizer)
    definition = recipe_definition()
    focal_definitions = definition.get("label_pairs")
    nonfocal_definitions = definition.get("nonfocal_tail_packs")
    _require(isinstance(focal_definitions, list) and
             len(focal_definitions) == 8,
             "production focal target bank count differs from 8")
    _require(isinstance(nonfocal_definitions, list) and
             len(nonfocal_definitions) == 4,
             "production nonfocal target bank count differs from 4")
    context = [dict(message) for message in _TARGET_BANK_CONTEXT]
    focal_probe = "What exact focal ledger word follows from the recorded rule?"
    focal_rows = []
    nonfocal_rows = []
    all_surfaces: list[str] = []
    for item in focal_definitions:
        _require(isinstance(item, Mapping) and
                 set(item) == {"id", "zero", "one"},
                 "production focal target bank schema differs")
        targets = (str(item["zero"]), str(item["one"]))
        evidence = _probe_evidence(
            tokenizer, context, focal_probe, targets,
            f"production focal bank {item['id']}")
        focal_rows.append({
            "bank_id": str(item["id"]),
            "target_0": targets[0],
            "target_1": targets[1],
            "probe_evidence": evidence,
        })
        all_surfaces.extend(targets)
    for item in nonfocal_definitions:
        _require(isinstance(item, Mapping) and set(item) == {
            "id", "location", "fact_name", "target", "countertarget", "probe",
        }, "production nonfocal target bank schema differs")
        targets = (str(item["target"]), str(item["countertarget"]))
        evidence = _probe_evidence(
            tokenizer, context, str(item["probe"]), targets,
            f"production nonfocal bank {item['id']}")
        nonfocal_rows.append({
            "bank_id": str(item["id"]),
            "fact_name": str(item["fact_name"]),
            "location": str(item["location"]),
            "target": targets[0],
            "countertarget": targets[1],
            "probe_evidence": evidence,
        })
        all_surfaces.extend(targets)
    folded = [unicodedata.normalize("NFKC", value).casefold()
              for value in all_surfaces]
    _require(len(folded) == 24 and len(set(folded)) == 24,
             "production target surfaces are not 24 mutually distinct values")
    _require(all(not left.startswith(right) and not right.startswith(left)
                 for index, left in enumerate(folded)
                 for right in folded[index + 1:]),
             "production target surfaces prefix across component banks")
    token_sequences = [
        tuple(target["token_ids"])
        for row in focal_rows + nonfocal_rows
        for target in row["probe_evidence"]["targets"]
    ]
    _require(len(token_sequences) == 24 and len(set(token_sequences)) == 24,
             "production target token sequences are not mutually distinct")
    _require(all(_nonprefix_ids(left, right)
                 for index, left in enumerate(token_sequences)
                 for right in token_sequences[index + 1:]),
             "production target token sequences prefix across component banks")
    bank_definition = {
        "focal": focal_definitions,
        "nonfocal": nonfocal_definitions,
    }
    core = {
        "schema": TARGET_BANK_SCHEMA,
        "design_id": DESIGN_ID,
        "scope": "PRODUCTION_COMPONENT_TARGET_BANKS_WITHOUT_CANDIDATE_TEXT",
        "status": "ALL_PRODUCTION_TARGET_BANKS_TOKENIZER_QUALIFIED",
        "execution_ready": False,
        "scientific_outcome": False,
        "in_pool_tuple_materialized": False,
        "permutation_seed_present": False,
        "literal_permutation_present": False,
        "focal_bank_count": len(focal_rows),
        "nonfocal_bank_count": len(nonfocal_rows),
        "target_surface_count": len(folded),
        "all_target_surfaces_mutually_distinct_nonprefix": True,
        "all_target_token_sequences_mutually_distinct_nonprefix": True,
        "bank_definition_sha256": sha256_json(bank_definition),
        "qualification_context_sha256": sha256_json(context),
        "tokenizer_binding": binding,
        "focal_banks": focal_rows,
        "nonfocal_banks": nonfocal_rows,
    }
    return {**core, "qualification_sha256": sha256_json(core)}


def _all_probe_contexts(tokenizer, fixture: Mapping[str, Any],
                        correct: dict[str, Any], wrong: dict[str, Any],
                        middle: int) -> dict[str, Any]:
    full_c = correct["completed_messages"]
    full_w = wrong["completed_messages"]
    fresh_c = full_c[:1] + full_c[middle:]
    fresh_w = full_w[:1] + full_w[middle:]
    _require(fresh_c == fresh_w,
             "C/W compact fresh visible messages differ")
    fresh_ids = _plain_int_sequence(
        canonical_ids_any(tokenizer, fresh_c, render_hf),
        "fresh probe-context token IDs",
        maximum_exclusive=len(tokenizer),
    )
    _require(fresh_ids == correct["fresh"].token_ids == wrong["fresh"].token_ids,
             "F probe context differs from exact fresh destination")
    contexts = {"C": full_c, "W": full_w, "F": fresh_c}
    focal = fixture["focal"]
    nonfocal = fixture["nonfocal_control"]
    result = {}
    for context_name, messages in contexts.items():
        result[context_name] = {
            "focal": _probe_evidence(
                tokenizer, messages, str(focal["probe"]),
                (str(focal["target"]), str(focal["countertarget"])),
                f"{context_name} focal"),
            "nonfocal": _probe_evidence(
                tokenizer, messages, str(nonfocal["probe"]),
                (str(nonfocal["target"]), str(nonfocal["countertarget"])),
                f"{context_name} nonfocal"),
        }
    return result


def validate_development_sentinel(
    tokenizer,
    fixture: Mapping[str, Any],
    *,
    carrier_content: str = FROZEN_TEST_CARRIER_CONTENT,
) -> dict[str, Any]:
    """Validate one exact out-of-pool family/subtype development sentinel."""

    binding = _tokenizer_binding(tokenizer)
    correct_messages, wrong_messages, middle, allowlist = _exact_pair_checks(
        fixture)
    carrier_ids = _plain_int_sequence(
        tokenizer.encode(carrier_content, add_special_tokens=False),
        "development carrier token IDs",
        maximum_exclusive=len(tokenizer),
    )
    attempt = carrier_attempt_spec(
        fixture, render_index=1, attempt_index=1)
    carrier = validate_carrier_attempt(
        tokenizer, fixture, carrier_content,
        attempt_spec=attempt,
        generated_content_ids=carrier_ids,
        termination_token_id=tokenizer.eos_token_id,
        hit_token_cap=False,
    )
    correct = _variant_plans(
        tokenizer, correct_messages, middle=middle,
        carrier_content=carrier_content, label="C")
    wrong = _variant_plans(
        tokenizer, wrong_messages, middle=middle,
        carrier_content=carrier_content, label="W")

    _require(correct["history"]["content_token_widths"] ==
             wrong["history"]["content_token_widths"],
             "C/W per-message production content widths differ")
    _require(correct["history"]["canonical_message_widths"] ==
             wrong["history"]["canonical_message_widths"],
             "C/W canonical message widths differ")
    _require(correct["completed"]["content_token_widths"] ==
             wrong["completed"]["content_token_widths"],
             "C/W completed per-message content widths differ")
    _require(correct["completed"]["canonical_message_widths"] ==
             wrong["completed"]["canonical_message_widths"],
             "C/W completed canonical message widths differ")
    require_matching_geometry(correct["native"], wrong["native"])
    require_matching_geometry(correct["turn"], wrong["turn"])
    _require(correct["fresh"] == wrong["fresh"],
             "C/W fresh destination plans differ")
    _require(correct["noncarrier_token_count"] ==
             wrong["noncarrier_token_count"],
             "C/W noncarrier skeleton counts differ")
    probes = _all_probe_contexts(
        tokenizer, fixture, correct, wrong, middle)

    def compact_variant(value: dict[str, Any]) -> dict[str, Any]:
        return {
            "history": value["history"],
            "completed": value["completed"],
            "noncarrier_token_count": value["noncarrier_token_count"],
            "role_native": value["native_events"],
            "turn_aligned": value["turn_events"],
            "fresh_destination": value["fresh_events"],
            "carrier_regions": asdict(value["native"].regions),
            "fresh_source_regions": asdict(value["fresh"].source_regions),
            "fresh_physical_regions": asdict(value["fresh"].physical_regions),
            "fresh_token_count": len(value["fresh"].token_ids),
            "fresh_token_ids_sha256": sha256_ints(value["fresh"].token_ids),
            "fresh_logical_positions_sha256": sha256_ints(
                value["fresh"].logical_positions),
        }

    core = {
        "schema": STIMULI_SCHEMA,
        "design_id": DESIGN_ID,
        "scope": "OUT_OF_POOL_DEVELOPMENT_SENTINEL_ONLY",
        "status": "MECHANICAL_SENTINEL_PASS_NO_EXECUTION_AUTHORIZATION",
        "execution_ready": False,
        "scientific_outcome": False,
        "pool_member": False,
        "in_pool_tuple_materialized": False,
        "permutation_seed_present": False,
        "literal_permutation_present": False,
        "stable_candidate_id": fixture.get("stable_candidate_id"),
        "stratum_id": fixture.get("stratum_id"),
        "resolution_mode": fixture.get("resolution_mode"),
        "fixture_sha256": sha256_json(fixture),
        "literal_history_pair_sha256": fixture.get(
            "literal_history_pair_sha256"),
        "tokenizer_binding": binding,
        "carrier": carrier,
        "pair": {
            "changed_message_allowlist": allowlist,
            "retained_tail_byte_identical": True,
            "per_message_production_widths_identical": True,
            "canonical_roundtrip_both_variants": True,
            "role_native_geometry_identical": True,
            "turn_aligned_geometry_identical": True,
            "fresh_destination_identical": True,
            "no_call_exceeds_4096": True,
        },
        "C": compact_variant(correct),
        "W": compact_variant(wrong),
        "probe_contexts": probes,
        "residual_requirements": [
            "independent target-aware carrier semantic review",
            "independent fixture content review",
            "ranked-candidate materialization only after seed/permutation commit",
            "Phase A subject eligibility and VP availability gates",
            "separate treatment release",
        ],
    }
    return {**core, "mechanical_evidence_sha256": sha256_json(core)}


def validate_all_development_sentinels(
    tokenizer,
    *,
    carrier_content: str = FROZEN_TEST_CARRIER_CONTENT,
) -> dict[str, Any]:
    """Validate exactly 8 families x 2 subtypes without touching the pool."""

    rows = []
    for stratum in STRATA:
        for explicit in (True, False):
            fixture = materialize_development_sentinel(
                stratum, explicit=explicit)
            evidence = validate_development_sentinel(
                tokenizer, fixture, carrier_content=carrier_content)
            rows.append({
                "stratum_id": stratum,
                "resolution_mode": evidence["resolution_mode"],
                "stable_candidate_id": evidence["stable_candidate_id"],
                "fixture_sha256": evidence["fixture_sha256"],
                "mechanical_evidence_sha256": evidence[
                    "mechanical_evidence_sha256"],
                "noncarrier_token_count": evidence["C"][
                    "noncarrier_token_count"],
                "completed_source_token_count": evidence["C"][
                    "completed"]["canonical_token_count"],
                "fresh_token_count": evidence["C"]["fresh_token_count"],
                "carrier_expansion_sha256": evidence["carrier"][
                    "forbidden_surface_expansion_sha256"],
                "status": evidence["status"],
            })
    _require(len(rows) == 16, "development sentinel matrix is not 8 x 2")
    target_banks = validate_production_target_banks(tokenizer)
    core = {
        "schema": STIMULI_SCHEMA,
        "design_id": DESIGN_ID,
        "scope": "ALL_16_OUT_OF_POOL_FAMILY_BY_SUBTYPE_SENTINELS",
        "status": "MECHANICAL_SENTINEL_MATRIX_PASS_NO_EXECUTION_AUTHORIZATION",
        "execution_ready": False,
        "scientific_outcome": False,
        "in_pool_tuple_materialized": False,
        "permutation_seed_present": False,
        "literal_permutation_present": False,
        "sentinel_count": len(rows),
        "tokenizer_binding": _tokenizer_binding(tokenizer),
        "frozen_test_carrier_utf8_sha256": hashlib.sha256(
            carrier_content.encode("utf-8")).hexdigest(),
        "production_target_bank_qualification": target_banks,
        "rows": rows,
        "residual_requirements": [
            "This audit does not authorize Phase A or treatment.",
            "No production-pool tuple, seed, rank, or permutation was materialized.",
            "Independent content and target-aware carrier reviews remain pending.",
        ],
    }
    return {**core, "audit_sha256": sha256_json(core)}


__all__ = [
    "CARRIER_ATTEMPT_SCHEMA",
    "CARRIER_ATTEMPT_INDICES",
    "CARRIER_CONTENT_TOKEN_CAP",
    "CARRIER_MAX_NEW_TOKENS",
    "CARRIER_MAX_SAMPLING_CALLS",
    "CARRIER_RENDER_INDICES",
    "COMPLETED_SOURCE_TOKEN_BOUNDS",
    "FORBIDDEN_SURFACE_SCHEMA",
    "FROZEN_TEST_CARRIER_CONTENT",
    "NONCARRIER_TOKEN_BOUNDS",
    "PINNED_CHAT_TEMPLATE_SHA256",
    "PINNED_TOKENIZER_BACKEND_SHA256",
    "PINNED_TOKENIZER_FILES",
    "PINNED_TOKENIZER_VOCAB_SHA256",
    "STIMULI_SCHEMA",
    "TARGET_BANK_SCHEMA",
    "V13StimulusError",
    "carrier_attempt_spec",
    "expand_carrier_forbidden_surfaces",
    "sha256_ints",
    "sha256_json",
    "validate_all_development_sentinels",
    "validate_carrier_attempt",
    "validate_development_sentinel",
    "validate_production_target_banks",
]
